version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  auth-service:
    container_name: authService
    build: ./auth-service
    volumes:
      - ./auth-service:/app
    env_file:
      - ./auth-service/.env
  middlewares:
    container_name: middlewares
    build: ./middlewares
    volumes:
      - ./middlewares:/app
  order-service: 
    container_name: orderService
    build: ./order-service
    volumes:
      - ./order-service:/app
    env_file:
      - ./order-service/.env
  product_service:
    container_name: productService
    build: ./product-service
    volumes:
      - ./product-service:/app
    env_file:
      - ./product-service/.env
